# 快捷键

$mod = SUPER

bind = $mod, T, exec, kitty
bind = $mod, Q, killactive
bind = $mod, R, exec, hyprctl reload
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
