# Hyprland 主配置文件

source = ~/.config/hypr/hyprland/general.conf
source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/execs.conf

# 显示器
monitor = eDP-1, 1920x1080@144, 0x0, 1

# NVIDIA 双显卡（如需）
# env = AQ_DRM_DEVICES, /dev/dri/card0
